### ISSUE TITLE
error in generating dataset in 3D-U-Net-Prostate-Segmentation

### ISSUE THREAD

**Issue by chetanm310** [jancio/3D-U-Net-prostate-segmentation#1]
hi 
I am getting error as
ValueError: invalid literal for int() with base 10: '1-01'

when I am running in my jupyter notebook local server help me 
![project](https://user-images.githubusercontent.com/67574205/164886409-d2cd1e06-87fc-46af-bed8-75e0b14faeed.PNG)

**Comment by jancio** [comment]
Hi,
Have a look here on how to resolve this kind of errors: 
https://stackoverflow.com/a/47764450
> "But you get a ValueError if you pass a string representation of a float into int, or a string representation of anything but an integer (including empty string). If you do want to pass a string representation of a float to an int, as @katyhuff points out above, you can convert to a float first, then to an integer:"

**Comment by shathaa1983** [comment]
Hi,

I got an error when generating the dataset
![image](https://user-images.githubusercontent.com/69587655/189996363-e2c1d577-a9f8-4568-91b6-eb614bc58837.png)
could you please help with this?

**Comment by jancio** [comment]
Try checking the key names available in the dataset and possibly adjust the code if the structure has changed.
